apiVersion: v1
kind: Service
metadata:
  name: service-production
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: micros
  ports:
    - name: client-screenrecorder
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: api-screenrecorder
      protocol: TCP
      port: 8080
      targetPort: 8080