apiVersion: v1
kind: Service
metadata:
  name: nlb-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: api-screenrecorder
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: client-screenrecorder
  type: LoadBalancer
  selector:
    app: micros