apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-production
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micros-production
  template:
    metadata:
      labels:
        app: micros-production
    spec:
      containers:
        - name: api-screenrecorder
          image: marceloregistry.azurecr.io/screenrecorder:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - name: client-screenrecorder
          image: marceloregistry.azurecr.io/apiusers:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
