apiVersion: v1
kind: Service
metadata:
  name: service-production
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: micros-production
  ports:
    - name: api-screenrecorder
      protocol: TCP
      port: 8081
      targetPort: 8080
