apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-production
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: api-screenrecorder
          image: marceloregistry.azurecr.io/apiusers:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
