apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-release
  namespace: release
  labels:
    app: micros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micros
  template:
    metadata:
      labels:
        app: micros
    spec:
      containers:
        - name: api-screenrecorder-r
          image: marceloregistry.azurecr.io/screenrecorder:release
          ports:
            - containerPort: 80
        - name: client-screenrecorder-r
          image: marceloregistry.azurecr.io/apiusers:release
          ports:
            - containerPort: 8080