apiVersion: v1
kind: Service
metadata:
  name: service-release
  namespace: release
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: IPLoadBalancer
    service.beta.kubernetes.io/azure-load-balancer-ipv4: 4.180.76.14
spec:
  type: LoadBalancer
  selector:
    app: micros
  ports:
    - name: client-screenrecorder
      protocol: TCP
      port: 80
      targetPort: 80
    - name: api-screenrecorder
      protocol: TCP
      port: 8080
      targetPort: 8080