apiVersion: v1
kind: Service
metadata:
  name: service-release
  namespace: release
spec:
  type: LoadBalancer
  selector:
    app: micros
  ports:
    - name: client-screenrecorder
      protocol: TCP
      port: 433
      targetPort: 443
    - name: api-screenrecorder
      protocol: TCP
      port: 8080
      targetPort: 8080