name: Build and Deploy API Users

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:  # Añadir esto para permitir ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Print repository status
        run: git log -1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u ${{ secrets.DOCKERUSERNAME }} --password-stdin

      - name: Build and push Docker image for API Users
        run: |
          docker build -t ${{ secrets.DOCKERUSERNAME }}/apiusers:latest -f Dockerfile .
          docker push ${{ secrets.DOCKERUSERNAME }}/apiusers:latest

      # Deploy to Kubernetes (optional)
      # - name: Configure kubectl
      #   uses: azure/k8s-set-context@v1
      #   with:
      #     kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # - name: Apply Kubernetes manifests
      #   run: |
      #     kubectl apply -f k8s-deployment.yaml -n resultados-space
